# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 2
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xcvu37p-fsvh2892-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.cache/wt [current_project]
set_property parent.project_path D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/arbiter.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/rtl/axi_ram.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/axis_arb_mux.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/rtl/axis_register.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/rtl/debounce_switch.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/c2h_dma/dma_client_port.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/c2h_dma/dma_if_pcie_us_wr.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/c2h_dma/dma_psdpram.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/rtl/fpga_core.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/c2h_dma/pcie_dma_c2h_top.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pcie_us_axi_master.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pcie_us_axi_master_rd.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pcie_us_axi_master_wr.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pcie_us_axil_master.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pcie_us_axis_cq_demux.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pcie_us_cfg.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pcie_us_msi.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/c2h_dma/priority_encoder.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/lib/pcie/rtl/pulse_merge.v
  D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/rtl/fpga.v
}
read_ip -quiet d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc]
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x0y0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga.xdc
set_property used_in_implementation false [get_files D:/guow_test/verilog-pcie-demo/example/VU37P/fpga_axi/fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fpga -part xcvu37p-fsvh2892-2L-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
